config/routes.rb
Blocitoff::Application.routes.draw do
  devise_for :users
  resources :users, only: [:update]

  resources :todos, only: [:new, :create, :index, :destroy]
  
  post '/todos/:id/complete', to: 'todos#complete'

  get 'about' => 'welcome#about'

  root to: "welcome#index"
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user

  default_scope {order('created_at')}

  def time_till_delete
    ((created_at + 8.days) - Time.now).to_i / (24 * 60 * 60)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!

  def index
    @todos = current_user.todos.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = current_user.todos.build(todo_params)
    
    if @todo.save
      redirect_to todos_path, notice: 'Your new Todo was saved.'
    else
      render :new, error: 'There was an error saving your Todo.  Please try again.'
    end
  end

  def destroy
    @todo = Todo.find(params[:id])

    if @todo.destroy
      redirect_to todos_path, notice: 'Todo item has been removed.'
    else
      redirect_to todos_path, error: 'There was an error removing the Todo item.  Please try again.'
    end    
  end

  def complete
    @todo = Todo.find(params[:id])
    @todo.update_attributes(completed: 'true')
    render :nothing => true
  end

  private

  def todo_params
    params.require(:todo).permit(:description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!

 def update
   if current_user.update_attributes(user_params)
     flash[:notice] = "User information updated"
     redirect_to edit_user_registration_path
   else
     render "devise/registrations/edit"
   end
 end

 private

 def user_params
   params.require(:user).permit(:name)
 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocitoff", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Todos", todos_path %></li>
      <% if current_user %>
        <li><%= link_to "Profile", edit_user_registration_path %></li>
      <% end %>
      <div class="pull-right user-info">
       <% if current_user %>
        Welcome back <%= current_user.name || current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
       <% else %>
         <%= link_to "Sign In", new_user_session_path %> or 
         <%= link_to "Sign Up", new_user_registration_path %>
       <% end %>
     </div>
    </ul>

    <% if flash[:notice] %>
      <br/>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <br/>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <br/>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/todos/index.html.erb
<h2>My Todo List</h2>
<div class="row">
  <% @todos.each do |todo| %>
    <div class="col-md-8 todo-container" id="todo-<%= todo.id %>">
    <% if todo.completed %>
      <div class="alert alert-warning todo-alert">
        <ul class="list-inline">
          <li><span class="glyphicon glyphicon-check todo-checkbox"></span></li>
          <li><s><%= todo.description %></s></li>
          <li class="pull-right"><s><%= pluralize(todo.time_till_delete, 'day') %> left</s></li>
    <% else %>
      <div class="alert alert-info todo-alert">
        <ul class="list-inline">
          <li><span class="glyphicon glyphicon-unchecked todo-checkbox"></span></li>
          <li><%= todo.description %></li>
          <li class="pull-right"><%= pluralize(todo.time_till_delete, 'day') %> left</li>
    <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>
<div class="row">
  <div class="col-md-8">
      <%= link_to "Create new Todo", new_todo_path %>
  </div>
</div>

app/views/todos/new.html.erb
<h2>Create Todo Item</h2>
<div class="row">
  <div class="col-md-8">
    <%= form_for Todo.new do |form| %>
      <div class="form-group">
        <%= form.text_field :description, autofocus: true, class: 'form-control', placeholder: 'Description' %>
      </div>
      <div class="form-group">
        <%= form.submit 'Save', class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>About Blocitoff</h1>
<p>Blocitoff is an application that allows members to create a single to-do list with self-destructing items. That’s right. Self-destructing. The idea is simple. If the to-do item is not important enough to complete within seven days, then it doesn’t belong on your list. Blocitoff is a great motivational tool for getting things done.</p>
<h2>Want to try it out?</h2>
<p>If you are interested in test-driving Blocitoff login using the following cedentials:</p>
<ul class="list-unstyled">
  <li>U: member@example.com</li>
  <li>P: helloworld</li>
</ul>
<h2>Want to see more?</h2>
<p>If you are interested in or have any questions about my work, please visit my site at <a href="http://www.soriafernando.com/" target="_blank">www.soriafernando.com</a>.</p>

app/views/welcome/index.html.erb
<br/>
<div class="jumbotron">
  <h1>Blocitoff</h1>
  <p>Blocitoff allows users to create their own self-destructing to-do lists to keep focused on  the things that really matter!</p>
  <p>
    <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>